package:
  name: 'nionswift-experimental'
  version: '0.7.19'

source:
  git_rev: 0.7.19
  git_url: https://github.com/nion-software/experimental.git

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  include_recipe: False

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python >=3.12
    - nionswift >=16.16,<17.0
    - niondata >=15.9,<16.0
    - nionui >=10.2,<11.0

test:
  imports:
    - nionswift_plugin.nion_experimental_tools

about:
  home: https://github.com/nion-software/experimental
  summary: "Experimental tools for Nion Swift."
  description: "Experimental tools for Nion Swift."

extra:
  recipe-maintainers:
    cmeyer
